<?php

declare(strict_types=1);

/**
 * Phase A regression test — proves that list-type placeholders get expanded
 * into one <w:p> per list item (preserving paragraph formatting) instead of
 * being collapsed into a single line-break blob.
 *
 * Runs fully offline — no Docker, no Symfony, no customer data.
 * The fixture is the synthetic `test_template.docx` generated by
 * `fixtures/create_template.php` (pure PhpWord, no customer IP).
 *
 * Usage:
 *   php tests/phase-a-lists.php
 *
 * Exit code is 0 on pass, 1 on any assertion failure.
 */

$fixture = __DIR__ . '/fixtures/test_template.docx';
if (!is_file($fixture)) {
    fwrite(STDERR, "FAIL: fixture missing: $fixture\n");
    exit(1);
}

$out = sys_get_temp_dir() . '/templatex_phase_a_out.docx';
copy($fixture, $out);

// --- Test data: realistic but fully synthetic. Mix of scalars and list items.
$listValues = [
    'benefits'                 => ['Firmenwagen', 'Bonus (15%)', 'Betriebliche Altersvorsorge', '30 Urlaubstage'],
    'languageslist'            => ['Deutsch (Muttersprache)', 'Englisch (C1)', 'Spanisch (A2)'],
    'otherskillslist'          => ['SAP ERP', 'MS Office 365', 'Jira / Confluence'],
    'relevantposlist'          => ['Head of Sales — ACME AG', 'Sales Director EMEA — Global Foo GmbH'],
    'relevantfortargetposlist' => ['8 Direct Reports', 'P&L Verantwortung 25 Mio EUR', 'Store-Fläche 4 500 m²'],
];

// --- Inline copy of the algorithm from TemplateXController::expandListParagraphs,
//     kept dependency-free so this test can run anywhere PHP is available.
function expandListParagraphs(string $docxPath, array $listValues): array
{
    $expanded = [];

    $zip = new ZipArchive();
    if ($zip->open($docxPath) !== true) {
        fwrite(STDERR, "FAIL: cannot open $docxPath\n");
        exit(1);
    }
    $xml = $zip->getFromName('word/document.xml');
    if ($xml === false) {
        $zip->close();
        fwrite(STDERR, "FAIL: cannot read word/document.xml\n");
        exit(1);
    }

    $originalXml = $xml;

    foreach ($listValues as $key => $items) {
        $placeholder = '{{' . $key . '}}';
        if (!str_contains($xml, $placeholder)) {
            continue;
        }

        $pattern = '#<w:p\b[^>]*>(?:(?!</w:p>).)*?' . preg_quote($placeholder, '#') . '(?:(?!</w:p>).)*?</w:p>#s';
        $count = 0;
        $xml = preg_replace_callback(
            $pattern,
            function (array $m) use ($placeholder, $items, &$count): string {
                $count++;
                if (empty($items)) {
                    return '';
                }
                $out = '';
                foreach ($items as $item) {
                    $escaped = htmlspecialchars((string) $item, ENT_XML1 | ENT_QUOTES, 'UTF-8');
                    if (preg_match('/\r|\n/', $escaped) === 1) {
                        $escaped = preg_replace('/\r\n|\r|\n/', '</w:t><w:br/><w:t>', $escaped);
                    }
                    $out .= str_replace($placeholder, $escaped, $m[0]);
                }
                return $out;
            },
            $xml
        );
        if ($count > 0) {
            $expanded[$key] = $count;
        }
    }

    if ($xml !== $originalXml) {
        $zip->addFromString('word/document.xml', $xml);
    }
    $zip->close();

    return $expanded;
}

$expanded = expandListParagraphs($out, $listValues);

// --- Assertions ---------------------------------------------------------
$zip = new ZipArchive();
$zip->open($out);
$finalXml = $zip->getFromName('word/document.xml');
$zip->close();

$fails = [];
$total = 0;

foreach ($listValues as $key => $items) {
    if (!isset($expanded[$key])) {
        $fails[] = "key '$key' was not expanded (regex did not match the host <w:p>)";
        continue;
    }

    if (str_contains($finalXml, '{{' . $key . '}}')) {
        $fails[] = "key '$key' still has leftover placeholder in XML";
    }

    $paragraphs = 0;
    foreach ($items as $item) {
        $needle = htmlspecialchars((string) $item, ENT_XML1 | ENT_QUOTES, 'UTF-8');
        if (str_contains($finalXml, $needle)) {
            $paragraphs++;
        }
    }
    if ($paragraphs !== count($items)) {
        $fails[] = sprintf(
            "key '%s': expected %d items in XML, found %d",
            $key,
            count($items),
            $paragraphs
        );
    }

    printf("  %-28s expanded=%d items_found=%d/%d\n", $key, $expanded[$key], $paragraphs, count($items));
    $total += $paragraphs;
}

// Quantitative sanity: the output must have MORE <w:p> elements than the input.
$origZip = new ZipArchive();
$origZip->open($fixture);
$origXml = $origZip->getFromName('word/document.xml');
$origZip->close();

$origParagraphs = substr_count($origXml, '<w:p ') + substr_count($origXml, '<w:p>');
$newParagraphs  = substr_count($finalXml, '<w:p ') + substr_count($finalXml, '<w:p>');
printf("\n  <w:p> count: before=%d, after=%d (delta=%d)\n", $origParagraphs, $newParagraphs, $newParagraphs - $origParagraphs);

if ($newParagraphs <= $origParagraphs) {
    $fails[] = "paragraph count did not increase — expansion clearly did not happen";
}

// Output handoff
printf("\n  output: %s\n", $out);
printf("  total list items rendered: %d\n", $total);

if (!empty($fails)) {
    echo "\nFAIL\n";
    foreach ($fails as $f) {
        echo "  - $f\n";
    }
    exit(1);
}

echo "\nPASS — phase A list expansion works on the synthetic fixture.\n";
exit(0);
